import React from 'react';
import { GoogleAnalytics } from '@next/third-parties/google';
import ReactQueryProvider from '@/lib/reactQuery/providers';
import './globals.css';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'DevFest BoilerPlate',
  description: 'Generated by create next app',
  metadataBase: new URL('https://devfest-boilerplate.vercel.app/'),
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <ReactQueryProvider>
          {/* Your layout content, including header, main content, footer, etc goes here. */}
          {children}
        </ReactQueryProvider>
      </body>
      <GoogleAnalytics gaId={`${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`} />
    </html>
  );
}
